export interface AudioStatResult {
  exists: boolean;
  sizeBytes: number;
}

export interface AudioReadResult {
  ok: boolean;
  bytes?: Uint8Array;
  mimeType?: string;
  reason?: string;
}

export interface AudioSaveResult {
  ok: boolean;
  path?: string;
  reason?: string;
}

export interface KwesiAudioApi {
  stat(filePath: string): Promise<AudioStatResult>;
  read(filePath: string): Promise<AudioReadResult>;
  save(filePath: string, suggestedName: string, kind: "export" | "download"): Promise<AudioSaveResult>;
  reveal(filePath: string): Promise<{ ok: boolean }>;
}

function realAudioApi(bridge: NonNullable<Window["kwesi"]>["audio"]): KwesiAudioApi {
  return {
    stat: (filePath) => bridge.stat(filePath),
    read: (filePath) => bridge.read(filePath),
    save: (filePath, suggestedName, kind) => bridge.save(filePath, suggestedName, kind),
    reveal: (filePath) => bridge.reveal(filePath),
  };
}

const MOCK_SAMPLE_RATE = 8000;
const MOCK_DURATION_SEC = 1.5;

/**
 * A minimal, valid 16-bit PCM mono WAV — silent, tiny, generated in-memory
 * rather than shipped as a binary asset. Used only by the browser-preview
 * mock below so the waveform player has something real to decode and play.
 */
export function buildSilentWav(
  sampleRate: number = MOCK_SAMPLE_RATE,
  durationSec: number = MOCK_DURATION_SEC,
): Uint8Array {
  const numSamples = Math.floor(sampleRate * durationSec);
  const dataSize = numSamples * 2;
  const buffer = new ArrayBuffer(44 + dataSize);
  const view = new DataView(buffer);

  function writeString(offset: number, str: string) {
    for (let i = 0; i < str.length; i += 1) view.setUint8(offset + i, str.charCodeAt(i));
  }

  writeString(0, "RIFF");
  view.setUint32(4, 36 + dataSize, true);
  writeString(8, "WAVE");
  writeString(12, "fmt ");
  view.setUint32(16, 16, true);
  view.setUint16(20, 1, true);
  view.setUint16(22, 1, true);
  view.setUint32(24, sampleRate, true);
  view.setUint32(28, sampleRate * 2, true);
  view.setUint16(32, 2, true);
  view.setUint16(34, 16, true);
  writeString(36, "data");
  view.setUint32(40, dataSize, true);

  return new Uint8Array(buffer);
}

/**
 * A minimal, valid Standard MIDI File (format 0, one track) holding a short
 * arpeggio — same idea as buildSilentWav above: generated in-memory so the
 * browser preview's piano roll has real notes to draw. Without this the mock
 * answered every read with WAV bytes, including `.mid` paths, and the
 * piano-roll viewer correctly rejected them ("Couldn't parse this MIDI
 * file") for every MIDI generation in the preview.
 */
export function buildDemoMidi(): Uint8Array {
  const TICKS_PER_BEAT = 480;
  const bytes: number[] = [];

  const pushStr = (s: string) => {
    for (let i = 0; i < s.length; i += 1) bytes.push(s.charCodeAt(i));
  };
  const pushUint32 = (n: number) => bytes.push((n >>> 24) & 0xff, (n >>> 16) & 0xff, (n >>> 8) & 0xff, n & 0xff);
  const pushUint16 = (n: number) => bytes.push((n >>> 8) & 0xff, n & 0xff);

  pushStr("MThd");
  pushUint32(6);
  pushUint16(0); // format 0
  pushUint16(1); // one track
  pushUint16(TICKS_PER_BEAT);

  // Track events are length-prefixed, so they're built separately first.
  const track: number[] = [];
  const pushVarLen = (value: number) => {
    const chunks = [value & 0x7f];
    let rest = value >>> 7;
    while (rest > 0) {
      chunks.unshift((rest & 0x7f) | 0x80);
      rest >>>= 7;
    }
    track.push(...chunks);
  };

  // C major / A minor arpeggios over four bars — enough shape that the
  // roll reads as music rather than a single flat line.
  const pitches = [60, 64, 67, 72, 71, 67, 64, 60, 57, 60, 64, 69, 67, 64, 60, 55];
  const step = TICKS_PER_BEAT / 2;
  const gap = 40; // silence between notes, so they read as separate blocks
  pitches.forEach((pitch, index) => {
    pushVarLen(index === 0 ? 0 : gap);
    track.push(0x90, pitch, 0x64); // note on
    pushVarLen(step - gap);
    track.push(0x80, pitch, 0x40); // note off
  });
  track.push(0x00, 0xff, 0x2f, 0x00); // end of track

  pushStr("MTrk");
  pushUint32(track.length);
  bytes.push(...track);

  return new Uint8Array(bytes);
}

function isMidiPath(filePath: string): boolean {
  const lower = filePath.toLowerCase();
  return lower.endsWith(".mid") || lower.endsWith(".midi");
}

/**
 * localStorage has no notion of real files on disk, so the mock treats
 * every request as playable and serves generated bytes matching what the
 * path claims to be — a silent WAV for audio, a real SMF for MIDI — good
 * enough to exercise play/pause/seek/export and the piano roll during a
 * plain browser preview without Electron. Real empty-vs-real-audio
 * detection only matters against the Electron main process's actual bytes.
 */
function createMockAudioApi(): KwesiAudioApi {
  const wav = buildSilentWav();
  const midi = buildDemoMidi();

  return {
    async stat(filePath) {
      return { exists: true, sizeBytes: (isMidiPath(filePath) ? midi : wav).byteLength };
    },
    async read(filePath) {
      return isMidiPath(filePath)
        ? { ok: true, bytes: midi, mimeType: "audio/midi" }
        : { ok: true, bytes: wav, mimeType: "audio/wav" };
    },
    async save(_filePath, suggestedName, kind) {
      console.log(`[mock audio] ${kind} requested for "${suggestedName}"`);
      return { ok: true, path: `/mock/${kind}/${suggestedName}` };
    },
    async reveal(filePath) {
      console.log(`[mock audio] reveal-in-folder requested for "${filePath}"`);
      return { ok: true };
    },
  };
}

export const kwesiAudio: KwesiAudioApi = window.kwesi?.audio
  ? realAudioApi(window.kwesi.audio)
  : createMockAudioApi();
